Traceback (most recent call last):
  File "c:\MyStuff\CodingProjects\enigmaCOA\trainModelLogisticRegression.py", line 106, in <module>
    y_predicted = model(x_train)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\MyStuff\CodingProjects\enigmaCOA\trainModelLogisticRegression.py", line 92, in forward
    y_predicited = torch.sigmoid(self.linear(x))
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (38516x1000 and 32768x1)